services:
  api_gateway:
    build: ./api_gateway
    container_name: shopapp_api
    ports:
      - "8000:8000"
    environment:
      # Add your AWS Public IP or Domain here, separated by commas
      # Example: http://localhost:8081,http://54.123.45.67:8081
      - CORS_ORIGINS=*
      - RABBITMQ_HOST=rabbitmq
      # CHECK AWS CONSOLE FOR CORRECT ENDPOINT. It usually starts with the instance ID (e.g., database-1)
      - DB_HOST=database-1.cgfs0ciy6cbx.us-east-1.rds.amazonaws.com
      - DB_USER=bestBuy
      - DB_PASSWORD=bestBuy23
      - DB_NAME=user
      - MONGO_URI=mongodb+srv://ikrgycloud_db_user:Ikrgy%40234@cluster0.awxtma5.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      # Mounts the code for development (remove for production to use built image)
       - ./api_gateway:/app

  worker:
    build: ./api_gateway
    container_name: shopapp_worker
    command: python routes/worker.py
    restart: on-failure
    environment:
      - DB_HOST=database-1.cgfs0ciy6cbx.us-east-1.rds.amazonaws.com
      - DB_USER=bestBuy
      - DB_PASSWORD=bestBuy23
      - DB_NAME=user
      - RABBITMQ_HOST=rabbitmq
      - MONGO_URI=mongodb+srv://ikrgycloud_db_user:Ikrgy%40234@cluster0.awxtma5.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./api_gateway:/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shopapp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5